[tool.poetry]
name = "contextvars-extras"
version = "0.1.0"
description = "contextvars made easy"
authors = ["Dmitry Vasilyanov <vdmit11@gmail.com>"]
exclude = []

[tool.poetry.dependencies]
python = "^3.7.1"
sphinx-rtd-theme = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
tox = "^3.22.0"
ipython = "^7.20.0"
Sphinx = "^3.5.1"
sphinx-autobuild = "^2020.9.1"
rpdb = "^0.1.6"
sphinx-toggleprompt = "^0.0.5"
sphinx-copybutton = "^0.3.1"
pylava = "^0.3.0"
pylava-pylint = "^0.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
