[tool.poetry]
name = "contextvars-extras"
version = "0.0.9"
description = "Contextvars made easy (WARNING: unstable alpha version. Things may break)."
license = "MIT"
authors = ["Dmitry Vasilyanov <vdmit11@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/vdmit11/contextvars-extras"
documentation = "https://contextvars-extras.readthedocs.io"
keywords = ["contextvars", "context", "async", "threading", "gevent"]
exclude = []
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.dependencies]
python = "^3.7.1"


[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
tox = "^3.24.1"
ipython = "^7.26.0"
Sphinx = "^4.1.2"
sphinx-autobuild = "^2021.3.14"
rpdb = "^0.1.6"
sphinx-toggleprompt = "^0.0.5"
sphinx-copybutton = "^0.4.0"
pylava = "^0.3.0"
pylava-pylint = "^0.0.3"
radon = "^5.1.0"
mypy = "^0.910"
pytest-mypy = "^0.8.1"
black = "^21.7b0"
isort = "^5.9.3"
pytest-black = "^0.3.12"
pytest-isort = "^2.0.0"
Flask = {extras = ["async"], version = "^2.0.1"}
gevent = "^21.8.0"
sphinx-rtd-theme = "^0.5.2"
pytest-cov = "^2.12.1"
python-semantic-release = "^7.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
upload_to_pypi = true
upload_to_release = true
build_command = "poetry build"
major_on_zero = false
