[tool.poetry]
name = "contextvars-extras"
version = "0.1.0"
description = "contextvars made easy"
authors = ["Dmitry Vasilyanov <vdmit11@gmail.com>"]
exclude = []

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
tox = "^3.22.0"
ipython = "^7.20.0"
Sphinx = "^3.5.1"
sphinx-autobuild = "^2020.9.1"
rpdb = "^0.1.6"
sphinx-toggleprompt = "^0.0.5"
sphinx-copybutton = "^0.3.1"
pylava = "^0.3.0"
pylava-pylint = "^0.0.3"
radon = "^4.3.2"
mypy = "^0.812"
pytest-mypy = "^0.8.0"
black = "^20.8b1"
isort = "^5.7.0"
pytest-black = "^0.3.12"
pytest-isort = "^1.3.0"
Flask = "^1.1.2"
gevent = "^21.8.0"
sphinx-rtd-theme = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
